# This is a basic workflow to help you get started with Actions

name: Build and Publish Gitbook

# Controls when the action will run. Triggers the workflow on push
# events but only for the master branch
on:
  push:
    branches: [ master ]

jobs:
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
    # Checks-out repository under so the job can access it
    - uses: actions/checkout@v2
    - name: Gitbook Action
      uses: zanderzhao/gitbook-action@v1.2.2
      with:
        token: ${{ secrets.PERSONAL_TOKEN }}
