# This is a basic workflow to help you get started with Actions

name: Build and Publish Gitbook

# Controls when the action will run. Triggers the workflow on push
# events but only for the master branch
on:
  push:
    branches: [ master ]

jobs:
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
    # Checks-out repository under so the job can access it
    - uses: actions/checkout@v2
    - name: Install Packages
      run: yarn install
    - name: Deploy to GH Pages
      run: |
        git config --global user.email "rachel.newman@argos.co.uk"
        git config --global user.name "rachelnewman"
        git remote set-url origin https://${{ secrets.PERSONAL_TOKEN }}@github.com/rachelnewman/findability-leaderboard.git
        yarn deploy
